export const ENV = {
  // WECHAT_PAY_MCHID: process.env['WECHAT_PAY_MCHID']!,
  // WECHAT_PAY_KEY: process.env['WECHAT_PAY_KEY']!,
  // WECHAT_PAY_CERT_PRI: process.env['WECHAT_PAY_CERT_PRI']!,
  // WECHAT_PAY_CERT_PUB: process.env['WECHAT_PAY_CERT_PUB']!,
  // WECHAT_PAY_CERT_SN: process.env['WECHAT_PAY_CERT_SN']!,
  // WECHAT_MINI_PROGRAM_APPID: process.env['WECHAT_MINI_PROGRAM_APPID']!,
  // WECHAT_MINI_PROGRAM_APPSECRET: process.env['WECHAT_MINI_PROGRAM_APPSECRET']!,
  // WECHAT_COMPONENT_APPID: process.env['WECHAT_COMPONENT_APPID']!,
  // WECHAT_COMPONENT_APPSECRET: process.env['WECHAT_COMPONENT_APPSECRET']!,
  // WECHAT_COMPONENT_MESSAGE_KEY: process.env['WECHAT_COMPONENT_MESSAGE_KEY']!,
  // WECHAT_COMPONENT_MESSAGE_TOKEN: process.env['WECHAT_COMPONENT_MESSAGE_TOKEN']!,

  // ALICLOUD_OSS_AK: process.env['ALICLOUD_OSS_AK']!,
  // ALICLOUD_OSS_SK: process.env['ALICLOUD_OSS_SK']!,
  // ALICLOUD_OSS_REGION: process.env['ALICLOUD_OSS_REGION']!,
  // ALICLOUD_OSS_HOST: process.env['ALICLOUD_OSS_HOST']!,
  // ALICLOUD_OSS_BUCKET: process.env['ALICLOUD_OSS_BUCKET']!,

  DINGTALK_MESSAGE_AK: process.env['DINGTALK_MESSAGE_AK']!,
  DINGTALK_MESSAGE_SK: process.env['DINGTALK_MESSAGE_SK']!,

  XCLOUD_AK: process.env['XCLOUD_AK']!,
  XCLOUD_BASE_URL: process.env['XCLOUD_BASE_URL']!,

  // YZH_DEALER_ID: process.env['YZH_DEALER_ID']!,
  // YZH_BROKER_ID: process.env['YZH_BROKER_ID']!,
  // YZH_APP_KEY: process.env['YZH_APP_KEY']!,
  // YZH_DES3_KEY: process.env['YZH_DES3_KEY']!,
  // YZH_PRIVATE_KEY: process.env['YZH_PRIVATE_KEY']!,
  // YZH_PUBLIC_KEY: process.env['YZH_PUBLIC_KEY']!,
};
